[package]
name = "first_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
futures = "0.3.16"
async-std = "1.9.0"
serde_json = "1.0.66"
serde = "1.0.127"
